os: linux
dist: xenial

sudo: required

language: generic

notifications:
  email:
    on_success: never
    on_failure: change

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

cache:
  apt: true
  directories:
    - $HOME/.composer/cache

env:
  global:
    - LOCAL_DIR: build
    # - COMPOSER_INSTALL: false
    - WP_INSTALL: true
    - PHP_FPM_UID: "`id -u`"
    - PHP_FPM_GID: "`id -g`"
    - WP_VERSION: latest
    - LOCAL_PHP_XDEBUG: true

jobs:
  include:
  - env: LOCAL_PHP=7.4-fpm WP_TRAVISCI=test:php
    name: "PHPUnit Tests: PHP 7.4"
  # - env: LOCAL_PHP=7.3-fpm WP_TRAVISCI=test:php
  #   name: "PHPUnit Tests: PHP 7.3"
  # - env: LOCAL_PHP=7.3-fpm LOCAL_PHP_MEMCACHED=true WP_TRAVISCI=test:php
  #   name: "PHPUnit Tests: PHP 7.3 with Memcached"
  # - env: LOCAL_PHP=7.2-fpm WP_TRAVISCI=test:php
  #   name: "PHPUnit Tests: PHP 7.2"
  # - env: LOCAL_PHP=7.1-fpm WP_TRAVISCI=test:php
  #   name: "PHPUnit Tests: PHP 7.1"
  # - env: LOCAL_PHP=7.0-fpm WP_TEST_REPORTER=true WP_TRAVISCI=test:php
  #   name: "PHPUnit Tests: PHP 7.0"
  # - env: LOCAL_PHP=5.6-fpm WP_TRAVISCI=test:php
  #   name: "PHPUnit Tests: PHP 5.6"
  # - env: LOCAL_PHP=8.0-fpm WP_TRAVISCI=test:php
  #   name: "PHPUnit Tests: PHP 8.0"
  # allow_failures:
  # - env: WP_TRAVISCI=test:compat COMPOSER_INSTALL=true NPM_INSTALL=false WP_INSTALL=false
  # - env: LOCAL_PHP=8.0-fpm WP_TRAVISCI=test:php
  fast_finish: true

# before_install:
# - bash bin/install-docker-compose.sh

before_script:
# - docker-compose up
- docker-compose run --rm web php --version
- docker-compose run --rm db mysql --version
# - docker-compose run db mysql -u db_user -pdb_password 

script:
- docker-compose run --rm web php -f ./php/index.php
# - phpunit
# - docker-compose run --rm wordpress composer --version
# - docker-compose run --rm wordpress php --version
# - docker-compose run db mysql --version
# - docker-compose run wordpress vendor/bin/phpunit
# - docker-compose run --rm wordpress_tests php --version
# - docker-compose run --rm composer composer global require phpunit/phpunit "^5 || ^6 || ^7"
# - docker-compose run --rm wordpress_tests php --version
# - docker-compose run --rm composer composer config --list --global
# - docker-compose run --rm composer /app/vendor/bin/phpunit
