os: linux
dist: xenial

sudo: required

language: generic

notifications:
  email:
    on_success: never
    on_failure: change

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

cache:
  apt: true
  directories:
    - $HOME/.composer/cache

env:
  global:
    - LOCAL_DIR: build
    # - COMPOSER_INSTALL: false
    - WP_INSTALL: true
    - PHP_FPM_UID: "`id -u`"
    - PHP_FPM_GID: "`id -g`"
    - WP_VERSION: 4.2

jobs:
  include:
  - env: LOCAL_PHP=7.4-fpm WP_TRAVISCI=test:php
    name: "PHPUnit Tests: PHP 7.4"
  # - env: LOCAL_PHP=7.3-fpm WP_TRAVISCI=test:php
  #   name: "PHPUnit Tests: PHP 7.3"
  # - env: LOCAL_PHP=7.3-fpm LOCAL_PHP_MEMCACHED=true WP_TRAVISCI=test:php
  #   name: "PHPUnit Tests: PHP 7.3 with Memcached"
  # - env: LOCAL_PHP=7.2-fpm WP_TRAVISCI=test:php
  #   name: "PHPUnit Tests: PHP 7.2"
  # - env: LOCAL_PHP=7.1-fpm WP_TRAVISCI=test:php
  #   name: "PHPUnit Tests: PHP 7.1"
  # - env: LOCAL_PHP=7.0-fpm WP_TEST_REPORTER=true WP_TRAVISCI=test:php
  #   name: "PHPUnit Tests: PHP 7.0"
  # - env: LOCAL_PHP=5.6-fpm WP_TRAVISCI=test:php
  #   name: "PHPUnit Tests: PHP 5.6"
  # - env: LOCAL_PHP=8.0-fpm WP_TRAVISCI=test:php
  #   name: "PHPUnit Tests: PHP 8.0"
  # allow_failures:
  # - env: WP_TRAVISCI=test:compat COMPOSER_INSTALL=true NPM_INSTALL=false WP_INSTALL=false
  # - env: LOCAL_PHP=8.0-fpm WP_TRAVISCI=test:php
  fast_finish: true

# before_install:
# - bash bin/install-docker-compose.sh

before_script:
# - bash bin/build-docker-containers.sh
# - docker-compose run -it --network wpdevnet --rm mysql mysql -hmysql -uroot -p
# - bash bin/install-wp-tests.sh wordpress_test root '' mysql $WP_VERSION
- docker-compose up -d
# - bash bin/install-wp-tests.sh wp_test_db wp_test_user wp_test_password db:3306 $WP_VERSION

script:
- phpunit
# - docker-compose run --rm phpunit phpunit
