version: '3.3'

services:
  #wordpress:
    # depends_on:
    #   - db
    # image: wordpress:${WP_VERSION}
    # volumes:
    #   - wordpress_files:/var/www/html
    # ports:
    #   - "80:80"
    # restart: always
    # environment:
    #   WORDPRESS_DB_HOST: db:3306
    #   WORDPRESS_DB_USER: wp_test_user
    #   WORDPRESS_DB_PASSWORD: wp_test_password

  wordpress:
    depends_on:
      - db
    volumes:
      # - wordpress_files:/tmp
      # - ./:/app
      - ./tests:/wordpress/tests
      - ./src:/wordpress/src
    build:
      context: .
      args:
        LOCAL_PHP_IMAGE: wordpressdevelop/php:${LOCAL_PHP-latest}
        DATABASE: wordpress_tests
        USER: wp_test_user
        PASSWORD: wp_test_password
        HOST: db:3306
        VER: ${WP_VERSION}
      environment:
        WAIT_HOSTS: mysql:3306
    # restart: always

  # phpunit:
  #   image: wordpressdevelop/phpunit:${LOCAL_PHP-latest}
  #   depends_on:
  #     - db
  #     - wordpress_tests
  #   volumes:
  #     - wordpress_files:/tmp
  #     - ./:/app

  # composer:
  #   image: composer:latest
  #   depends_on:
  #     - wordpress_tests
  #   volumes:
  #     - wordpress_files:/tmp
  #     - ./:/app
  #   # restart: no

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - '3306:3306'
    expose:
      - '3306'
      MYSQL_DATABASE: wordpress_tests
      MYSQL_USER: wp_test_user
      MYSQL_PASSWORD: wp_test_password
    # healthcheck:
    #   test: "/usr/bin/mysql --user=wp_test_user --password=wp_test_password --execute \"SHOW DATABASES;\""
    #   interval: 3s
    #   timeout: 1s
    #   retries: 5

volumes:
    wordpress_files:
    db_data:
    
