version: '3.3'

services:
  wordpress:
    depends_on:
      - db
    image: wordpress:${WP_VERSION}
    volumes:
      - wordpress_files:/var/www/html
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_test_user
      WORDPRESS_DB_PASSWORD: wp_test_password

  wordress_tests:
    depends_on:
      - wordpress
    volumes:
      - wordpress_files:/var/www/html
    build: .
    restart: always
    stdin_open: true
    tty: true

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pawwsord
      MYSQL_DATABASE: wp_test_db
      MYSQL_USER: wp_test_user
      MYSQL_PASSWORD: wp_test_password
volumes:
    wordpress_files:
    db_data:
